music_app/config/routes.rb
MusicApp::Application.routes.draw do


  resources :songs do
    resources :comments
  end

  

  resources :users

  get '/login', to: 'sessions#new', as: :login
  get '/logout', to: 'sessions#destroy', as: :logout
  resources :sessions
  
  root to: "home#index"

  match 'songs/:song_id/comments/:id', to: 'comments#flag', as: :comments_flag
  match 'songs/:song_id/comments/:id', to: 'comments#changeflag', as: :comments_changeflag

  match '/admin', to: 'admin#index', as: :admin

  match 'tagged' => 'users#tagged', :as => 'tagged'


end

music_app/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  before_validation :set_default_role

  acts_as_taggable_on :tags

  

  mount_uploader :artist_image, ArtistImageUploader
  mount_uploader :banner_image, ArtistBannerUploader

  attr_accessible :background_colour, :main_body_colour, :header_font_colour, :artist_image, :banner_image, :artist_name, :bio, :email, :password, :website, :password_confirmation, :tag_list

  has_many :songs, dependent: :destroy
  has_many :comments, dependent: :destroy


  validates :password, presence: true, on: :create

  validates :email, presence: true

  validates :email, uniqueness: true

  validates :artist_name, uniqueness: true

  validates :artist_name, presence: true

  validates_length_of :bio, :maximum => 1000, :message => "less than 1000 characters if you don't mind"
  validates_length_of :header_font_colour, :maximum => 6

  def role?(role)
    self.role.to_s == role.to_s
  end


  def self.artists
    joins(:songs).group('songs.user_id').having('count(*) > 0')
  end


  private
  def set_default_role
    self.role ||= "artist"
  end


  








end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
   load_and_authorize_resource
  # GET /users
  # GET /users.json

  def tagged
  if params[:tag].present? 
    @users = User.tagged_with(params[:tag])
    @tag = params[:tag]
  else 
    @users = User.all
  end  
  end


  def index
    @users = User.artists.order('artist_name')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    

    if @user.save
      session[:user_id] = @user.id unless current_user
      redirect_to users_path, notice: "Signed up!"
    else
      render "new"
    end

  end


  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    if current_user.role == "admin"
      redirect_to admin_path
    else
      respond_to do |format|
        format.html { redirect_to users_url }
        format.json { head :no_content }
      end
    end
  end
end

music_app/app/helpers/users_helper.rb
module UsersHelper
  include ActsAsTaggableOn::TagsHelper
end

music_app/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, {placeholder: "Required!"} %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
   <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :artist_name, 'User/Artist name' %><br />
    <%= f.text_field :artist_name, {placeholder: "Required!"}  %>
  </div>
  
  
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio, {placeholder: "Optional! Max 1000 characters"}  %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website, {placeholder: "eg. www.band.com"} %>
  </div>
  <div class="field">
  <%= f.label :tags %>
  <%= f.text_field :tag_list, {placeholder: "split tags with commas"}%>
  </div>

  <h2>Customise Your Artist Profile!</h2>
  <div class="field">
    <%= f.label :artist_image %><br />
    <%= f.file_field :artist_image %>
  </div>
  <div class="field">
    <%= f.label :banner_image %><br />
    <%= f.file_field :banner_image %>
  </div>
  <div class="field">
    <%= f.label :header_font_colour %><br />
    <%= f.text_field :header_font_colour, {placeholder: "RGB format eg.DD44G4"} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

music_app/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
<%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %>

music_app/app/views/users/index.html.erb
<h1>Artists</h1>


<% @users.each do |user| %>
   <div class = "index_item"> 
  
  <%= link_to image_tag(user.artist_image.thumb.url), user_path(user) %>
  
  <h3><%= user.artist_name %></h3>
  </div>
<% end %>


<br />

music_app/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email, {placeholder: "Required!"} %>
      </div>
      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password, {placeholder: "Required!"} %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </div>
      <div class="field">
        <%= f.label :artist_name %>
        <%= f.text_field :artist_name, {placeholder: "Required!"} %>
      </div>
      
      <div class="actions"><%= f.submit %></div>
    <% end %>


<%= link_to 'Back', users_path %>

music_app/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="user_banner">
  <%= image_tag @user.banner_image.url %>
  <% if @user.header_font_colour%>
  <p id="text" style="color: #<%=@user.header_font_colour%>;"><%=  @user.artist_name %></p>
  <%else%>
  <p id="text"><%=  @user.artist_name %></p>
  <%end%>

</div>




  <div class = "artist_details">
  <%= image_tag @user.artist_image.detail.url %>
  <p>

  <h2>tags</h2>
    <% @user.tags.any? %>
    <% @user.tags.each do |tag| %>
    <%= link_to tag.name, tagged_url(:tag => tag.name) %>
    <% end %>
    <br>
    <br>
    <b>About:</b>
    <%= @user.bio %>
  </p>

  <h3>
    <b>Website:</b>
    <a href="http://<%= @user.website %>"><%= @user.website %></a>
  </h3>

 

  <div class = "discography">
<h2>Songs</h2>

  <% @user.songs.each do |song| %>
    <div class = "index_item">
    <%= link_to image_tag(song.image.thumb.url), song_path(song) %>  
  <tr>
    <audio controls>
    <source src="<%= song.song_file %>" type="audio/mpeg" width=200px>
  Your browser does not support the audio element.
  </audio>
    <h3><%= song.title %><br><span>by </span><%=link_to song.user.artist_name, user_path(song.user)%></h3>
  </tr>
</div>  
<% end %>
  </table>
 </div> 
</div>

 <div class = "artist_options">
<% if can? :manage, @user %>
<h2><%= link_to 'Add Song', new_song_path %></h2>
<h3><%= link_to 'Edit Profile', edit_user_path(@user) %></h3>
<h3><%= link_to 'Delete Profile', @user, method: :delete, data: { confirm: 'Are you sure?' } %></h3>
<%end%>

<div>

<div id = "clear"></div>

music_app/app/views/users/tagged.html.erb
<h2>Artists tagged with "<%=@tag%>"</h2>


<% @users.each do |user| %>
   <div class = "index_item"> 
  
  <%= link_to image_tag(user.artist_image.thumb.url), user_path(user) %>
  
  <h3><%= user.artist_name %></h3>
  </div>
<% end %>


<br />