music_app/config/routes.rb
MusicApp::Application.routes.draw do


  resources :songs do
    resources :comments
  end

  

  resources :users

  get '/login', to: 'sessions#new', as: :login
  get '/logout', to: 'sessions#destroy', as: :logout
  resources :sessions
  
  root to: "home#index"

  match 'songs/:song_id/comments/:id', to: 'comments#flag', as: :comments_flag
  match 'songs/:song_id/comments/:id', to: 'comments#changeflag', as: :comments_changeflag

  match '/admin', to: 'admin#index', as: :admin

  match 'tagged' => 'users#tagged', :as => 'tagged'


end

music_app/app/views/admin/index.html.erb
<div class = "home">
  <h1>Users</h1>
  <table>
    <tr>
      <th>ID</th>
        <th>Joined</th>
        <th>Artist Name</th>
        <th>Email</th>
        <th>Role</th>
      </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.created_at.strftime("%d %B %Y")%></td>
      <td><%= user.artist_name%></td>
        <td><%=user.email%></td>
        <td><%=user.role%></td>
        <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %><td>
        <td><%= link_to 'Show', user_path(user)%></td>
    </tr>
    <%end%>
  </table>
</div>


<div class = "home">
  <h1>Songs</h1>
<table>
    <tr>
      <th>ID</th>
        <th>Created</th>
        <th>Title</th>
        <th>Artist</th>
      </tr>

  <% @songs.each do |song| %>
    <tr>
      <td><%= song.id %></td>
      <td><%= song.created_at.strftime("%d %B %Y")%></td>
      <td><%= song.title%></td>
        <td><%=song.user.artist_name%></td>
        <td><%= link_to 'Delete', song, method: :delete, data: { confirm: 'Are you sure?' } %><td>
        <td><%= link_to 'Show', song_path(song)%></td>
    </tr>
    <%end%>
  </table>
 </div>

<div class = "home">
<h1>Comments</h1>
  <table>
    <tr>
      <th>Comment ID</th>
        <th>Date Posted</th>
        <th>Song</th>
        <th>Posted by</th>
        <th>Flagged?</th>
      </tr>
  <% @comments.each do |comment| %>
    <tr>
      <td><%= comment.id %></td>
      <td><%= comment.created_at.strftime("%d %B %Y")%></td>
      <td><%= comment.song.title%></td>
        <td><%=comment.user.artist_name%></td>
        <td><%=comment.flagged%></td>
        <td><%= link_to 'Delete', [comment.song, comment], method: :delete, data: { confirm: 'Are you sure?' } %><td>
        <td><%= link_to 'Show', song_comment_path(comment.song, comment)%></td>
        <td><%= link_to 'Change Flag', [comment.song, comment], method: :flag, data: { confirm: 'Are you sure you want to change flag?' } %> </td>

    </tr>
    <%end%>
    <br class="clear" />
  </ul>