music_app/config/routes.rb
MusicApp::Application.routes.draw do


  resources :songs do
    resources :comments
  end

  

  resources :users

  get '/login', to: 'sessions#new', as: :login
  get '/logout', to: 'sessions#destroy', as: :logout
  resources :sessions
  
  root to: "home#index"

  match 'songs/:song_id/comments/:id', to: 'comments#flag', as: :comments_flag
  match 'songs/:song_id/comments/:id', to: 'comments#changeflag', as: :comments_changeflag

  match '/admin', to: 'admin#index', as: :admin

  match 'tagged' => 'users#tagged', :as => 'tagged'


end

music_app/app/models/song.rb
class Song < ActiveRecord::Base


  attr_accessible :about, :image, :lyrics, :title, :user_id, :song_file

  

  mount_uploader :song_file, SongFileUploader
  mount_uploader :image, ArtistImageUploader


  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :song_file, presence: true
  validates_length_of :title, :maximum => 50
  validates_length_of :title, :maximum => 500



end

music_app/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  load_and_authorize_resource
  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.order('title')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songs }
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.find(params[:id])
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/new
  # GET /songs/new.json
  def new
    @song = Song.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(params[:song])
    @song.user = current_user

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.json
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    if current_user.role == "admin"
      redirect_to admin_path
    else

      respond_to do |format|
        format.html { redirect_to songs_url }
        format.json { head :no_content }
      end
    end
  end
end

music_app/app/helpers/songs_helper.rb
module SongsHelper
end

music_app/app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, {placeholder: "Required! max 50 characters"} %>
  </div>
  <div class="field">
    <%= f.label :about %><br />
    <%= f.text_area :about,  {placeholder: "Optional! max 500 characters"}%>
  </div>
  <div class="field">
    <%= f.label :song_file %><br />
    <%= f.file_field :song_file %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
 

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

music_app/app/views/songs/_form_comment.erb
<%= form_for([@song, @comment]) do |f| %>

  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment, {placeholder: "Max length 1000 characters"} %>
  </div>
 
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

music_app/app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

music_app/app/views/songs/index.html.erb
<h1>Songs</h1>

<% @songs.each do |song| %>
<div class = "index_item">
    <%= link_to image_tag(song.image.thumb.url), song_path(song) %>  
  <tr>
    <audio controls>
    <source src="<%= song.song_file %>" type="audio/mpeg" width=200px>
  Your browser does not support the audio element.
  </audio>
    <h3><%= song.title %><br><span>by </span><%=link_to song.user.artist_name, user_path(song.user)%></h3>
  </tr>
</div>  
<% end %>
</table>

<br />

music_app/app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

music_app/app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>
<div class = "song_container">
  <div class = "player_large">
    <%= image_tag @song.image.detail.url %><br>
    
  </div>


  <div class = "song_details">
    <h1>
      <%= @song.title %>
    </h1>
    <h3>
      by <%= link_to @song.user.artist_name, user_path(@song.user) %>
    </h3>
    <audio controls>
    <source src="<%= @song.song_file %>" type="audio/mpeg">
  Your browser does not support the audio element.
  </audio>
    <p>
      <b>About:</b>
      <%= @song.about %>
    </p>
    
  </div>

  <div class = "song_options">
    <% if can? :manage, @song %>
      <%= link_to 'Edit', edit_song_path(@song) %> 
      <%= link_to 'Delete', @song, method: :delete, data: { confirm: 'Are you sure?' } %>
    <%end%>
    
  </div> 
  <br class="clear" />
</div>

    
<div class = "comments_container">
  <h2>Comments</h2>
  <%= render 'form_comment' %> 
  <ul>
  <% @song.comments.each do |comment| %>
    <li>
      <div class = "comment_item">
      <div class = "comment_image">
        <%= image_tag comment.user.artist_image.thumb.url %>
      </div>
      <div class = "comment_detail">
        <%if comment.flagged == true%>
        <p><%= "**Comment flagged for moderation**"%></p>
        <%else%>
        <p>"<%= comment.comment %>"<p>
          <%end%>
          
        <h3><%= comment.updated_at.strftime("%d %B %Y")%> by 
        <%=link_to comment.user.artist_name, user_path(comment.user)%></h3>
      </div><br>
      
      <h3>
        <% if can? :manage, comment %>
        <%= link_to 'Delete', [@song, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
        <%end%>
      
      <% if can? :flag, comment%>
      <%= link_to 'Flag', [@song, comment], method: :flag, data: { confirm: 'Are you sure you want to flag?' } %>
      <%end%>
        </h3>
      
      <%end%>

      </div>
    
    </li><br>
    <br class="clear" />
  </ul>

</div>
  