music_app/config/routes.rb
MusicApp::Application.routes.draw do


  resources :songs do
    resources :comments
  end

  

  resources :users

  get '/login', to: 'sessions#new', as: :login
  get '/logout', to: 'sessions#destroy', as: :logout
  resources :sessions
  
  root to: "home#index"

  match 'songs/:song_id/comments/:id', to: 'comments#flag', as: :comments_flag
  match 'songs/:song_id/comments/:id', to: 'comments#changeflag', as: :comments_changeflag

  match '/admin', to: 'admin#index', as: :admin

  match 'tagged' => 'users#tagged', :as => 'tagged'


end

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Music Forum</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
</head>

  <body>


  <div class = "main_container">
    <div class = "header">
      <div id = "logo"><h1> general ensemble //</h1></div>
      <div id = "welcome">
        <% if current_user %>
          <h3>Hi <%=current_user.artist_name%>
          <%= link_to ' // logout', logout_path %></h3>
        <%else%>
          <h3><%= link_to 'sign up  |', new_user_path %>
          <%= link_to 'login', login_path %></h3> 
        <%end%>

        
      </div>  
    </div>  
      <div class = "nav"> 
        <ul id="list_in_a_row">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'Artists', users_path %></li>      
            <li><%= link_to 'Songs', songs_path %></li> 
            <%if current_user%>  
            <li><%= link_to 'My Profile', user_path(current_user)%></li>
            <%end%>
            <%if current_user && current_user.role == "admin"%>
            <li><%= link_to 'Admin', admin_path%></li>
            <%end%> 
            <% flash.each do |name, msg| %>
          <li class="flash-message flash-message-<%= name %>">
            <%= msg %>
            <% end %>
          </li>
        
        </li>   
        </ul>
      </div>
  
  
    <div id = "views"> 

    <%= yield %>
  </div>
  </div>
    
</body>
</html>